service: todo-application-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  lists:
    handler: handler.lists
    events:
      - http:
          path: lists
          method: get
          cors: true
      - http:
          path: lists/{listId}
          method: delete
          cors: true
      - http:
          path: lists
          method: post
          cors: true
      - http:
          path: lists/{listId}
          method: put
          cors: true
